package MyException.AtomStructureException;

import MyException.CircularOrbitExceotion.ObjectDoesNotExistException;

public class ElectronDoesNotExistExistException extends ObjectDoesNotExistException {
}
